apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eksdemo
  template:
    metadata:
      labels:
        app: eksdemo
    spec:
      containers:
        - name: back-end
          image: 669796221703.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latest
          ports:
            - containerPort: 8080
